### ISSUE TITLE
mail seller when real estate is purchased

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPRealEstate#7]
**As** a server OP
**I want** to inform sellers when they sell real estate
**Because** occasionally players don't know for weeks.

Mail format to match GPAuctions.

/mail send [seller] &f[&6GPAuctions&f] &a[buyer]&b has purchased your Land Claim at &a[coordinates] &b. The sale price was &a[ListingPriceonSign]&b.

I don't know if it's the same, but lets mail when subclaims are sold also.

/mail send [seller] &f[&6GPAuctions&f] &a[buyer]&b has purchased your Subclaim at &a[coordinates] &b. The sale price was &a[ListingPriceonSign]&b.

Optional questions:

**Is your feature request related to a problem? Please describe.**
Informs seller when sales complete. 

**Describe alternatives you've considered**
None.

**Comment by RoboMWM** [comment]
hmm, thought I had the gherkin given, when, then statements in the template. Guess not.

**Comment by RoboMWM** [comment]
also, the why should be written for the player 
as a player
I want a /mail when my real estate on the market makes a sale
Because I don't have any other way of knowing without checking the estate myself

**Comment by RoboMWM** [comment]
given a player with a pending estate or whatever
when the estate sells
then the player should receive a /mail in the following format: blahblah

**Comment by RoboMWM** [comment]
idk if the code distinguishes between claims and subclaims, my guess is that it treats them the same.

**Comment by NullCase** [comment]
Hi RoboMWM

I don't know if there's a question in there or if you are thinking out loud about templates. Either is fine by me :)

Regarding the code, if it treats claims and subclaims the same, then this ought to work:

/mail send [seller] &f[&6GPAuctions&f] &a[buyer]&b has purchased your claim at &a[coordinates] &b. The sale price was &a[ListingPriceonSign]&b.

**Comment by NullCase** [comment]
Hi @RoboMWM It looks like maybe you just got busy. In case i should mention, from my end it seems like there's no rush so you're welcome to take your time.

If something comes up where you want a response, I'll be checking Github.

**Comment by RoboMWM** [comment]
No, idk if you see it but I implemented this feature and am waiting your feedback. 

I suppose I should've commented as well

**Comment by RoboMWM** [comment]
The marker that GitHub put here https://github.com/RoboMWM/GPRealEstate/issues/7#ref-commit-3f679b6

**Comment by RoboMWM** [comment]
> I don't know if there's a question in there or if you are thinking out loud about templates. Either is fine by me :)

More of suggesting improvements. Usually you want to write stories in the perspective of the subject that will be receiving the feature. Makes sense for ops to have admin tools while players have player features like this one.

**Comment by NullCase** [comment]
> No, idk if you see it but I implemented this feature and am waiting your feedback.

It's implemented? That sounds great to me. I don't know how to code... which is going to be annoying.

What I notice in the code is:

```
" &f[&6GPAuctions&f] &a[buyer]&b has purchased your claim at &a[coordinates] &b. The sale price was &a[ListingPriceonSign]&b.");
```
And it seems like buyer, coordinates, and list price are intended to update with the person, place, and price.

It looks like time to test it out. How do I download the .jar?

**Comment by RoboMWM** [comment]
oh
right I just copied it, Kinda assumed that the square brackets was just formatting like the prefix. Guess I gotta edit the event to include the buyer and the price.

**Comment by RoboMWM** [comment]
It still would've worked though, just without the placeholders filled out. Jar link should be in releases, that link should always point to the latest build's jar.

**Comment by NullCase** [comment]
always latest, OK thanks.

**Comment by NullCase** [comment]
Purchased a land claim and this error was thrown:

```

[03:15:40] [Server thread/ERROR]: Could not pass event GPRSaleEvent to GPRealEstate v1.6.0
--
java.lang.NullPointerException: null
at me.SuperPyroManiac.GPR.feature.MailSellerOnSale.onSale(MailSellerOnSale.java:35) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor299.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-129]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-129]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-129]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-129]
at me.SuperPyroManiac.GPR.GPREListener.makePayment(GPREListener.java:78) ~[?:?]
at me.SuperPyroManiac.GPR.GPREListener.onSignInteract(GPREListener.java:342) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor297.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-129]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-129]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-129]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-129]
at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:463) ~[patched_1.15.2.jar:git-Paper-129]
at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:448) ~[patched_1.15.2.jar:git-Paper-129]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1378) ~[patched_1.15.2.jar:git-Paper-129]
at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.15.2.jar:git-Paper-129]
at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.15.2.jar:git-Paper-129]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-129]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-129]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-129]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-129]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-129]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-129]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-129]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-129]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-129]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-129]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]


```

**Comment by RoboMWM** [comment]
Whenever I figure out how to efficiently develop software via test-driven development (which I'm trying to do with GP v20) these dumb mistakes will hopefully be less frequent.

**Comment by NullCase** [comment]
Looks good! Nice work RoboMWM.
